# serverless.yml
service: all-data-exporter-service

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  stage: ${opt:stage, "development"}

functions:
  getExportedData:
    handler: source/main.getExportedData
    events:
      - http:
          path: getExportedData/{stage}
          method: get
          cors: true
  getExportedDataList:
    handler: source/main.getExportedDataList
    events:
      - http:
          path: getExportedDataList
          method: get
          cors: true

plugins:
  - fullstack-serverless

custom:
  fullstack:
    bucketName: deployed-bucket
    distributionFolder: ../client/builds/web
    indexDocument: index.html
